# Generated by Django 4.0.6 on 2022-10-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0003_chatroom_websocket_url_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
