# Generated by Django 4.0.6 on 2022-10-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0004_remove_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
