# Generated by Django 4.0.6 on 2022-10-10 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0005_message_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
