# Generated by Django 4.0.6 on 2022-10-11 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0007_remove_chatroom_users_remove_message_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='other_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
